############ USER #######################
### User sing up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Sergio Perez",
    "company": "Red Bull Racing",
    "address": "Guadalajara - Mexico",
    "phone": "3794-1234456",
    "email": "checo11@redbull.com",
    "password": "123456"
}

### User sing in endpoint (Nuevo Token)
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "checo11@redbull.com",
    "password": "12345678"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWNvMTFAcmVkYnVsbC5jb20iLCJpYXQiOjE2MjA5MTkyMzYsImV4cCI6MTYyMDkyMDEzNn0.-E-Krbz-q8ZzxdeNqhFFBOgPZRU2aNRL4X0PO17ZPKo

{
    "email": "checo11@redbull.com",
    "password": "123456"
}


############### Token routers #######################


### Get refreshed token
GET http://localhost:3001/v1/tokens
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWNvMTFAcmVkYnVsbC5jb20iLCJpYXQiOjE2MjA5MTkyNzIsImV4cCI6MTYyMDkyMDE3Mn0.zwp7UGcURHntgMiGomTIWqEq-3MX7SiJMdOqiGqulHs

### password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "checo11@redbull.com"
}

### Update new password endpoints
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "checo11@redbull.com",
    "pin": 576189,
    "newPassword": "12345678"
}

### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWNvMTFAcmVkYnVsbC5jb20iLCJpYXQiOjE2MjEwOTE5MzMsImV4cCI6MTYyMTA5MjgzM30.0y-Iqz0NxuYMG-P6hy_7uQXKeQPe9MkVYNZts-9iyy8


############ TICKETS #######################

POST http://localhost:3001/v1/ticket
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWNvMTFAcmVkYnVsbC5jb20iLCJpYXQiOjE2MjE1MTIwMjAsImV4cCI6MTYyMTUxMjkyMH0.9Npa3mKA_mHOshugOcLt-gKy4yYEp3zWyKuUQSGG14Y

{
    "subject": "Form Issue",
    "sender": "Lewis",
    "message": "Contact form not working. Please fix it as soon as posible"
}


### Get all tickets
GET http://localhost:3001/v1/ticket/60a3e56608742a3c58de2635
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWNvMTFAcmVkYnVsbC5jb20iLCJpYXQiOjE2MjE1MTIwMjAsImV4cCI6MTYyMTUxMjkyMH0.9Npa3mKA_mHOshugOcLt-gKy4yYEp3zWyKuUQSGG14Y


### Get ticket by Id
GET http://localhost:3001/v1/ticket/60a417102043e220cc06dccb
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWNvMTFAcmVkYnVsbC5jb20iLCJpYXQiOjE2MjE1MTIwMjAsImV4cCI6MTYyMTUxMjkyMH0.9Npa3mKA_mHOshugOcLt-gKy4yYEp3zWyKuUQSGG14Y

